# Generated by Django 4.2.29 on 2026-03-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='send_whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
