# Generated by Django 4.2.20 on 2026-03-08 06:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={'ordering': ['user__first_name', 'user__last_name', 'user__username']},
        ),
        migrations.AddField(
            model_name='lease',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='lease',
            name='due_day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lease',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lease',
            name='lease_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lease',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='move_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='termination_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='alternate_phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='resident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='emergency_phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='resident',
            name='employer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resident',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='move_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resident',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='occupation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='resident',
            name='status',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Active'), ('notice', 'Notice Given'), ('former', 'Former'), ('blocked', 'Blocked')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('renewed', 'Renewed')], default='pending', max_length=32),
        ),
    ]
