# Generated by ChatGPT to add tenant scoping to property/unit models.

from django.db import migrations, models
import django.db.models.deletion


def set_default_tenant(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    Property = apps.get_model("properties", "Property")
    Unit = apps.get_model("properties", "Unit")

    try:
        public_tenant = Tenant.objects.get(schema_name="public")
    except Tenant.DoesNotExist:
        return

    Property.objects.filter(tenant__isnull=True).update(tenant=public_tenant)
    Unit.objects.filter(tenant__isnull=True).update(tenant=public_tenant)


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="properties",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="units",
                to="tenants.tenant",
            ),
        ),
        migrations.RunPython(set_default_tenant, reverse_code=migrations.RunPython.noop),
    ]
