# Generated by Django 4.2.20 on 2026-03-08 06:51

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_domain_options_alter_tenant_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0002_add_tenant_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('lease', 'Lease'), ('identity', 'Identity'), ('receipt', 'Receipt'), ('inspection', 'Inspection'), ('invoice', 'Invoice'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('object_id', models.PositiveBigIntegerField()),
                ('is_private', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['property__name', 'unit_number']},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='property',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lot_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='management_type',
            field=models.CharField(choices=[('self_managed', 'Self Managed'), ('agency_managed', 'Agency Managed')], default='self_managed', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='market_rent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_spaces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='postal_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='total_units',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='availability_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='floor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='unit',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='square_feet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('commercial', 'Commercial'), ('mixed_use', 'Mixed Use'), ('hostel', 'Hostel'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='property',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='vacant', max_length=32),
        ),
        migrations.AlterField(
            model_name='unit',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_property_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('property', 'unit_number'), name='unique_unit_number_per_property'),
        ),
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['content_type', 'object_id'], name='properties__content_e657ad_idx'),
        ),
    ]
