export const endpoints = {
  auth: {
    login: "/auth/login/",
    tokenRefresh: "/auth/token/refresh/",
    register: "/auth/register/",
    logout: "/auth/logout/",
    me: "/auth/me/",
    passwordReset: "/auth/password-reset/",
    passwordResetConfirm: "/auth/password-reset/confirm/",
    tenantSummary: "/auth/portal/tenant/summary/",
    ownerSummary: "/auth/portal/owner/summary/",
    caretakerSummary: "/auth/portal/caretaker/summary/",
    tenantInvoices: "/auth/portal/tenant/invoices/",
    tenantPayments: "/auth/portal/tenant/payments/",
    tenantMaintenance: "/auth/portal/tenant/maintenance-requests/",
    caretakerTasks: "/auth/portal/caretaker/tasks/",
  },
  properties: "/properties/",
  tenants: "/tenants/residents/",
  leases: "/tenants/leases/",
  invoices: "/invoices/",
  payments: "/payments/",
  bankPayments: "/payments/bank/record/",
  mpesa: "/payments/mpesa/initiate/",
  arrears: "/arrears/",
  expenses: "/expenses/",
  reports: {
    rentRoll: "/reports/rent-roll/",
    agedReceivables: "/reports/aged-receivables/",
    propertyProfitLoss: "/reports/property-profit-loss/",
  },
  notifications: "/notifications/",
  preferences: "/notification-preferences/",
  conversations: "/conversations/",
  messages: "/messages/",
  caretakers: "/caretakers/",
  maintenanceRequests: "/maintenance-requests/",
  maintenanceSchedules: "/maintenance-schedules/",
} as const;

export type Endpoints = typeof endpoints;
