# Generated by Django 4.2.20 on 2026-03-08 09:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_domain_options_alter_tenant_options_and_more'),
        ('tenants_app', '0002_alter_resident_options_lease_billing_cycle_and_more'),
        ('properties', '0003_document_alter_property_options_alter_unit_options_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank')], max_length=20)),
                ('transaction_type', models.CharField(choices=[('stk_push', 'STK Push'), ('c2b_callback', 'C2B Callback'), ('bank_transfer', 'Bank Transfer'), ('manual_bank_posting', 'Manual Bank Posting')], max_length=30)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('account_reference', models.CharField(blank=True, max_length=120)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('merchant_request_id', models.CharField(blank=True, max_length=255)),
                ('checkout_request_id', models.CharField(blank=True, max_length=255)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('bank_account_name', models.CharField(blank=True, max_length=255)),
                ('bank_account_number', models.CharField(blank=True, max_length=100)),
                ('result_code', models.CharField(blank=True, max_length=50)),
                ('result_description', models.TextField(blank=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_transactions', to='payments.invoice')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gateway_transactions', to='tenants_app.lease')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_transaction', to='payments.payment')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gateway_transactions', to='properties.property')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gateway_transactions', to='tenants_app.resident')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gateway_transactions', to='properties.unit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'gateway', 'status', 'created_at'], name='payments_pa_tenant__8d9dd9_idx'), models.Index(fields=['checkout_request_id'], name='payments_pa_checkou_2172be_idx'), models.Index(fields=['external_reference'], name='payments_pa_externa_50d042_idx')],
            },
        ),
    ]
