# Generated by Django 4.2.29 on 2026-03-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentgatewaytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='detected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='detected_expense_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='detected_vendor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expense',
            name='ocr_extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='ocr_failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='ocr_provider',
            field=models.CharField(choices=[('mock', 'Mock'), ('text', 'Text Extractor'), ('ocr_space', 'OCR.Space')], default='mock', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='ocr_raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='expense',
            name='ocr_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='ocr_status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='not_requested', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentgatewaytransaction',
            name='callback_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewaytransaction',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewaytransaction',
            name='last_webhook_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentgatewaytransaction',
            name='max_retry_count',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='paymentgatewaytransaction',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewaytransaction',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentgatewaytransaction',
            name='webhook_event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='paymentgatewaytransaction',
            index=models.Index(fields=['status', 'next_retry_at'], name='payments_pa_status_22be25_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentgatewaytransaction',
            index=models.Index(fields=['webhook_event_id'], name='payments_pa_webhook_4cea5e_idx'),
        ),
    ]
