export const routePaths = {
  root: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  dashboard: "/app",
  reports: "/app/reports",
  properties: "/app/properties",
  propertiesNew: "/app/properties/new",
  tenants: "/app/tenants",
  tenantsNew: "/app/tenants/new",
  payments: "/app/payments",
  arrears: "/app/arrears",
  expenses: "/app/expenses",
  expensesNew: "/app/expenses/new",
  notifications: "/app/notifications",
  maintenance: "/app/maintenance",
  maintenanceNew: "/app/maintenance/new",
  messages: "/app/messages",
  tenantPortal: "/app/tenant-portal",
  admin: "/admin",
} as const;
